/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import SubMenu.*;
import java.awt.Color;
import java.awt.PopupMenu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;
import utility.PanelRound;

/**
 *
 * @author rayrayaray
 */
public class MenuUtama extends javax.swing.JFrame {

    Color activeColor = new Color(0, 132, 161);
    Color nonActiveColor = new Color(0, 0, 0, 0);

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        Tampil_jam(label_jam);

        titleMenu.setText("Dashboard");

        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);
        DashboardFrame df = new DashboardFrame();
        jDesktopPane1.add(df);

        df.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleMenu = new javax.swing.JLabel();
        titleAkun = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        MenuBar = new javax.swing.JPanel();
        Dashboard = new utility.PanelRound();
        icon_dashboard = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JLabel();
        Transaksi = new utility.PanelRound();
        icon_transaksi = new javax.swing.JLabel();
        btn_transaksi = new javax.swing.JLabel();
        Pelanggan = new utility.PanelRound();
        icon_pelanggan = new javax.swing.JLabel();
        btn_pelanggan = new javax.swing.JLabel();
        DataPaket = new utility.PanelRound();
        icon_dataPaket = new javax.swing.JLabel();
        btn_dataPaket = new javax.swing.JLabel();
        Laporan = new utility.PanelRound();
        icon_laporan = new javax.swing.JLabel();
        btn_laporan = new javax.swing.JLabel();
        Karyawan = new utility.PanelRound();
        icon_karyawan = new javax.swing.JLabel();
        btn_karyawan = new javax.swing.JLabel();
        Keluar = new javax.swing.JPanel();
        icon_keluar = new javax.swing.JLabel();
        btn_keluar = new javax.swing.JLabel();
        label_jam = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleMenu.setFont(new java.awt.Font("Poppins", 1, 50)); // NOI18N
        titleMenu.setForeground(new java.awt.Color(1, 176, 213));
        titleMenu.setText("TITLE HERE");
        getContentPane().add(titleMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 40, 320, 90));

        titleAkun.setFont(new java.awt.Font("Poppins", 1, 26)); // NOI18N
        titleAkun.setForeground(new java.awt.Color(1, 176, 213));
        titleAkun.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titleAkun.setText("Akun");
        getContentPane().add(titleAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 390, 60));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 1100, 630));

        MenuBar.setOpaque(false);

        Dashboard.setBackground(new java.awt.Color(0, 132, 161));
        Dashboard.setRoundBottomRight(60);
        Dashboard.setRoundTopRight(60);
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
        });
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/dashboard.png"))); // NOI18N
        Dashboard.add(icon_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        btn_dashboard.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        btn_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_dashboard.setText("Dashboard");
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
        });
        Dashboard.add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 170, 50));

        Transaksi.setBackground(new java.awt.Color(0, 132, 161));
        Transaksi.setRoundBottomRight(60);
        Transaksi.setRoundTopRight(60);
        Transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransaksiMouseClicked(evt);
            }
        });
        Transaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/transaksi.png"))); // NOI18N
        Transaksi.add(icon_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        btn_transaksi.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        btn_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        btn_transaksi.setText("Transaksi");
        btn_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseExited(evt);
            }
        });
        Transaksi.add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 150, 50));

        Pelanggan.setBackground(new java.awt.Color(0, 132, 161));
        Pelanggan.setRoundBottomRight(60);
        Pelanggan.setRoundTopRight(60);
        Pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PelangganMouseClicked(evt);
            }
        });
        Pelanggan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/pelanggan.png"))); // NOI18N
        Pelanggan.add(icon_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        btn_pelanggan.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        btn_pelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btn_pelanggan.setText("Pelanggan");
        btn_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pelangganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pelangganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pelangganMouseExited(evt);
            }
        });
        Pelanggan.add(btn_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 150, 50));

        DataPaket.setBackground(new java.awt.Color(0, 132, 161));
        DataPaket.setRoundBottomRight(60);
        DataPaket.setRoundTopRight(60);
        DataPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataPaketMouseClicked(evt);
            }
        });
        DataPaket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_dataPaket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/data paket.png"))); // NOI18N
        DataPaket.add(icon_dataPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        btn_dataPaket.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        btn_dataPaket.setForeground(new java.awt.Color(255, 255, 255));
        btn_dataPaket.setText("Data Paket");
        btn_dataPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dataPaketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dataPaketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dataPaketMouseExited(evt);
            }
        });
        DataPaket.add(btn_dataPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 150, 50));

        Laporan.setBackground(new java.awt.Color(0, 132, 161));
        Laporan.setRoundBottomRight(60);
        Laporan.setRoundTopRight(60);
        Laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LaporanMouseClicked(evt);
            }
        });
        Laporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/laporan.png"))); // NOI18N
        Laporan.add(icon_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        btn_laporan.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        btn_laporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan.setText("Laporan");
        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_laporanMouseExited(evt);
            }
        });
        Laporan.add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 150, 50));

        Karyawan.setBackground(new java.awt.Color(0, 132, 161));
        Karyawan.setRoundBottomRight(60);
        Karyawan.setRoundTopRight(60);
        Karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KaryawanMouseClicked(evt);
            }
        });
        Karyawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/karyawan.png"))); // NOI18N
        Karyawan.add(icon_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        btn_karyawan.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        btn_karyawan.setForeground(new java.awt.Color(255, 255, 255));
        btn_karyawan.setText("Karyawan");
        btn_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_karyawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_karyawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_karyawanMouseExited(evt);
            }
        });
        Karyawan.add(btn_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 150, 50));

        Keluar.setOpaque(false);
        Keluar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/logout.png"))); // NOI18N
        Keluar.add(icon_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 60));

        btn_keluar.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        btn_keluar.setForeground(new java.awt.Color(255, 255, 255));
        btn_keluar.setText("Keluar");
        Keluar.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 170, 60));

        javax.swing.GroupLayout MenuBarLayout = new javax.swing.GroupLayout(MenuBar);
        MenuBar.setLayout(MenuBarLayout);
        MenuBarLayout.setHorizontalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addGroup(MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DataPaket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Karyawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MenuBarLayout.setVerticalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DataPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(MenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 560));

        label_jam.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        label_jam.setForeground(new java.awt.Color(1, 176, 213));
        label_jam.setText("jam");
        getContentPane().add(label_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 100, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/layout/Template Admin.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tampil_jam(JLabel jlabel) {
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "", nol_menit = "", nol_detik = "";

                java.util.Date dateTime = new java.util.Date();
                int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();

                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }

                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);

                jlabel.setText(jam + ":" + menit + ":" + detik + "");
            }
        };
        new Timer(1000, taskPerformer).start();
    }

    private void setHoverMenu() {
        if (titleMenu.getText().equals("Dashboard")) {
            Dashboard.setBackground(activeColor);
            Transaksi.setBackground(nonActiveColor);
            Pelanggan.setBackground(nonActiveColor);
            DataPaket.setBackground(nonActiveColor);
            Laporan.setBackground(nonActiveColor);
            Karyawan.setBackground(nonActiveColor);
        } else if (titleMenu.getText().equals("Transaksi")) {
            Dashboard.setBackground(nonActiveColor);
            Transaksi.setBackground(activeColor);
            Pelanggan.setBackground(nonActiveColor);
            DataPaket.setBackground(nonActiveColor);
            Laporan.setBackground(nonActiveColor);
            Karyawan.setBackground(nonActiveColor);
        } else if (titleMenu.getText().equals("Pelanggan")) {
            Dashboard.setBackground(nonActiveColor);
            Transaksi.setBackground(nonActiveColor);
            Pelanggan.setBackground(activeColor);
            DataPaket.setBackground(nonActiveColor);
            Laporan.setBackground(nonActiveColor);
            Karyawan.setBackground(nonActiveColor);
        } else if (titleMenu.getText().equals("Data Paket")) {
            Dashboard.setBackground(nonActiveColor);
            Transaksi.setBackground(nonActiveColor);
            Pelanggan.setBackground(nonActiveColor);
            DataPaket.setBackground(activeColor);
            Laporan.setBackground(nonActiveColor);
            Karyawan.setBackground(nonActiveColor);
        } else if (titleMenu.getText().equals("Laporan")) {
            Dashboard.setBackground(nonActiveColor);
            Transaksi.setBackground(nonActiveColor);
            Pelanggan.setBackground(nonActiveColor);
            DataPaket.setBackground(nonActiveColor);
            Laporan.setBackground(activeColor);
            Karyawan.setBackground(nonActiveColor);
        } else if (titleMenu.getText().equals("Karyawan")) {
            Dashboard.setBackground(nonActiveColor);
            Transaksi.setBackground(nonActiveColor);
            Pelanggan.setBackground(nonActiveColor);
            DataPaket.setBackground(nonActiveColor);
            Laporan.setBackground(nonActiveColor);
            Karyawan.setBackground(activeColor);
        }
    }

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
        titleMenu.setText("Dashboard");

        Dashboard.setBackground(activeColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        DashboardFrame df = new DashboardFrame();
        jDesktopPane1.add(df);
        df.setVisible(true);

    }//GEN-LAST:event_DashboardMouseClicked

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        titleMenu.setText("Dashboard");

        Dashboard.setBackground(activeColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        DashboardFrame df = new DashboardFrame();
        jDesktopPane1.add(df);
        df.setVisible(true);
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void TransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransaksiMouseClicked
        titleMenu.setText("Transaksi");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(activeColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        TransaksiFrame tf = new TransaksiFrame();
        jDesktopPane1.add(tf);
        tf.setVisible(true);
    }//GEN-LAST:event_TransaksiMouseClicked

    private void btn_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseClicked
        titleMenu.setText("Transaksi");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(activeColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        TransaksiFrame tf = new TransaksiFrame();
        jDesktopPane1.add(tf);
        tf.setVisible(true);
    }//GEN-LAST:event_btn_transaksiMouseClicked

    private void PelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PelangganMouseClicked
        titleMenu.setText("Pelanggan");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(activeColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        PelangganFrame pf = new PelangganFrame();
        jDesktopPane1.add(pf);
        pf.setVisible(true);
    }//GEN-LAST:event_PelangganMouseClicked

    private void btn_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pelangganMouseClicked
        titleMenu.setText("Pelanggan");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(activeColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        PelangganFrame pf = new PelangganFrame();
        jDesktopPane1.add(pf);
        pf.setVisible(true);
    }//GEN-LAST:event_btn_pelangganMouseClicked

    private void DataPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPaketMouseClicked
        titleMenu.setText("Data Paket");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(activeColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        DataPaketFrame dpf = new DataPaketFrame();
        jDesktopPane1.add(dpf);
        dpf.setVisible(true);
    }//GEN-LAST:event_DataPaketMouseClicked

    private void btn_dataPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataPaketMouseClicked
        titleMenu.setText("Data Paket");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(activeColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        DataPaketFrame dpf = new DataPaketFrame();
        jDesktopPane1.add(dpf);
        dpf.setVisible(true);
    }//GEN-LAST:event_btn_dataPaketMouseClicked

    private void LaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanMouseClicked
        titleMenu.setText("Laporan");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(activeColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        LaporanFrame lf = new LaporanFrame();
        jDesktopPane1.add(lf);
        lf.setVisible(true);
    }//GEN-LAST:event_LaporanMouseClicked

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        titleMenu.setText("Laporan");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(activeColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        LaporanFrame lf = new LaporanFrame();
        jDesktopPane1.add(lf);
        lf.setVisible(true);
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void KaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KaryawanMouseClicked
        titleMenu.setText("Karyawan");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(activeColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        KaryawanFrame kf = new KaryawanFrame();
        jDesktopPane1.add(kf);
        kf.setVisible(true);
    }//GEN-LAST:event_KaryawanMouseClicked

    private void btn_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_karyawanMouseClicked
        titleMenu.setText("Karyawan");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(activeColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        KaryawanFrame kf = new KaryawanFrame();
        jDesktopPane1.add(kf);
        kf.setVisible(true);
    }//GEN-LAST:event_btn_karyawanMouseClicked

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        Dashboard.setBackground(activeColor);
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
        setHoverMenu();
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseEntered
        Transaksi.setBackground(activeColor);
    }//GEN-LAST:event_btn_transaksiMouseEntered

    private void btn_transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseExited
        setHoverMenu();
    }//GEN-LAST:event_btn_transaksiMouseExited

    private void btn_pelangganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pelangganMouseEntered
        Pelanggan.setBackground(activeColor);
    }//GEN-LAST:event_btn_pelangganMouseEntered

    private void btn_pelangganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pelangganMouseExited
        setHoverMenu();
    }//GEN-LAST:event_btn_pelangganMouseExited

    private void btn_dataPaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataPaketMouseEntered
        DataPaket.setBackground(activeColor);
    }//GEN-LAST:event_btn_dataPaketMouseEntered

    private void btn_dataPaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataPaketMouseExited
        setHoverMenu();
    }//GEN-LAST:event_btn_dataPaketMouseExited

    private void btn_laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseEntered
        Laporan.setBackground(activeColor);
    }//GEN-LAST:event_btn_laporanMouseEntered

    private void btn_laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseExited
        setHoverMenu();
    }//GEN-LAST:event_btn_laporanMouseExited

    private void btn_karyawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_karyawanMouseEntered
        Karyawan.setBackground(activeColor);
    }//GEN-LAST:event_btn_karyawanMouseEntered

    private void btn_karyawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_karyawanMouseExited
        setHoverMenu();
    }//GEN-LAST:event_btn_karyawanMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utility.PanelRound Dashboard;
    private utility.PanelRound DataPaket;
    private utility.PanelRound Karyawan;
    private javax.swing.JPanel Keluar;
    private utility.PanelRound Laporan;
    private javax.swing.JPanel MenuBar;
    private utility.PanelRound Pelanggan;
    private utility.PanelRound Transaksi;
    private javax.swing.JLabel background;
    private javax.swing.JLabel btn_dashboard;
    private javax.swing.JLabel btn_dataPaket;
    private javax.swing.JLabel btn_karyawan;
    private javax.swing.JLabel btn_keluar;
    private javax.swing.JLabel btn_laporan;
    private javax.swing.JLabel btn_pelanggan;
    private javax.swing.JLabel btn_transaksi;
    private javax.swing.JLabel icon_dashboard;
    private javax.swing.JLabel icon_dataPaket;
    private javax.swing.JLabel icon_karyawan;
    private javax.swing.JLabel icon_keluar;
    private javax.swing.JLabel icon_laporan;
    private javax.swing.JLabel icon_pelanggan;
    private javax.swing.JLabel icon_transaksi;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel label_jam;
    private javax.swing.JLabel titleAkun;
    private javax.swing.JLabel titleMenu;
    // End of variables declaration//GEN-END:variables

}
