/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package MainMenu;

import javax.swing.JOptionPane;
import koneksi.Connect;
import java.sql.*;

/**
 *
 * @author perlengkapan
 */
public class Verification extends javax.swing.JFrame {
    
    int kodeVerifikasi, idAkun;
    
    /** Creates new form Verification */
    public Verification() {
        initComponents();
    }
    
    public void getVerif(int kodeVerif, int id){
        this.kodeVerifikasi = kodeVerif;
        this.idAkun = id;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_otp = new javax.swing.JTextField();
        txt_passBaru = new javax.swing.JTextField();
        txt_konfirmPassBaru = new javax.swing.JTextField();
        btn_reset = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_otp.setBackground(new java.awt.Color(217, 217, 217));
        txt_otp.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        txt_otp.setForeground(new java.awt.Color(0, 0, 0));
        txt_otp.setBorder(null);
        getContentPane().add(txt_otp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 370, 30));

        txt_passBaru.setBackground(new java.awt.Color(217, 217, 217));
        txt_passBaru.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        txt_passBaru.setForeground(new java.awt.Color(0, 0, 0));
        txt_passBaru.setBorder(null);
        getContentPane().add(txt_passBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 370, 40));

        txt_konfirmPassBaru.setBackground(new java.awt.Color(217, 217, 217));
        txt_konfirmPassBaru.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        txt_konfirmPassBaru.setForeground(new java.awt.Color(0, 0, 0));
        txt_konfirmPassBaru.setBorder(null);
        getContentPane().add(txt_konfirmPassBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 370, 30));

        btn_reset.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_reset.setText("Atur Ulang Kata Sandi");
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMouseClicked(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 430, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/layout/Reset Password Page.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseClicked
        if (txt_otp.getText().equals(String.valueOf(this.kodeVerifikasi))) {
            if (txt_passBaru.getText().equals(txt_konfirmPassBaru.getText())) {
                try{
                    Connection conn = Connect.GetConnection();
                    String sql = "UPDATE akun SET PASSWORD = '"+ txt_passBaru.getText() +"' WHERE id_akun = "+ this.idAkun +"";
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.executeUpdate();
                    
                    JOptionPane.showMessageDialog(null, "Password anda telah diperbarui, silahkan melakukan proses login");
                    this.setVisible(false);
                    new LoginPage().setVisible(true);
                    
                }catch(Exception e){
                    System.out.println(e.getMessage());
                }
            }else{
                JOptionPane.showMessageDialog(null, "Password beda");
                txt_passBaru.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Silahkan cek kembali kode verifikasi yang telah dikirimkan melalui email");
            txt_otp.requestFocus();
        }
    }//GEN-LAST:event_btn_resetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btn_reset;
    private javax.swing.JTextField txt_konfirmPassBaru;
    private javax.swing.JTextField txt_otp;
    private javax.swing.JTextField txt_passBaru;
    // End of variables declaration//GEN-END:variables

}
