/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SubMenu.popUp;

import SubMenu.DashboardFrame;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import koneksi.Connect;

/**
 *
 * @author Shila
 */
public class popUp_ketikkode extends javax.swing.JFrame {

    /**
     * Creates new form popUp_ketikkode
     */
    public popUp_ketikkode() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaPelanggan = new javax.swing.JLabel();
        confirm = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kembali = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaPelanggan.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        namaPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namaPelangganMouseClicked(evt);
            }
        });
        getContentPane().add(namaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 130, 30));

        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmMouseClicked(evt);
            }
        });
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 120, 30));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 270, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, 80, 20));

        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/img/popUp/popUp Ketik Kode.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        // TODO add your handling code here:
          dispose();

    }//GEN-LAST:event_kembaliMouseClicked

    private void confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseClicked
        // TODO add your handling code here:
    String code = jTextField1.getText();
    int codetransaksi;

    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    try {
        codetransaksi = Integer.parseInt(code);

        conn = Connect.GetConnection(); 
        stmt = conn.createStatement();
        rs = stmt.executeQuery("SELECT nama_pelanggan\n" +
                                "FROM transaksi t\n" +
                                "JOIN pelanggan p\n" +
                                "ON t.id_pelanggan = p.id_pelanggan"); 
         while (rs.next()) {                     
                        String nama = null;
                        nama = rs.getString("nama_pelanggan"); 
                        
                    }
        
        String sql = "UPDATE detail_transaksi SET status = 'sudah diambil', tgl_pesan = CURDATE() WHERE id_transaksi = " + codetransaksi;
        int rowsAffected = stmt.executeUpdate(sql); 
        if (rowsAffected > 0) {                     
            System.out.println("Sukses update");
        } else {
            System.out.println("Gagal update");
        }
        dispose();
    }  catch (SQLException ex) {
            Logger.getLogger(DashboardFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_confirmMouseClicked

    private void namaPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaPelangganMouseClicked
        // TODO add your handling code here:
        String code = namaPelanggan.getText();
        String namaPelanggan;
        
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
        try {
            namaPelanggan = code;
            conn = Connect.GetConnection();
            stmt = conn.createStatement();
            rs   = stmt.executeQuery("SELECT namaPelanggan FROM pelanggan");
            while (rs.next()) {
                String nama = null;
                nama = rs.getString("namaPelanggan");                
            }
            String sql = "SELECT namaPelanggan FROM pelanggan";
            int rowsAffected = stmt.executeUpdate(sql);
            if (rowsAffected > 0) {
                System.out.println("Sukses");                
            } else {
                System.out.println("Gagal");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DashboardFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_namaPelangganMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popUp_ketikkode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popUp_ketikkode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popUp_ketikkode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popUp_ketikkode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popUp_ketikkode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel kembali;
    private javax.swing.JLabel namaPelanggan;
    // End of variables declaration//GEN-END:variables
}
